### ISSUE TITLE
campaign update price

### ISSUE THREAD

**Issue by larrygrandslammedia** [EXADS/exads-api-client-php#10]
When i using you API update campaign price always shows me   following error message:
{
  "message": "[\"Campaign pricing minimum CPM price for Afghanistan is 0.500&euro;.\"]"
}
My test update campaign data is following , campaign is target by country Afghanistan only with some carrier.
"pricing": {
    "model": 2,
    "price": 1.2
  },

**Comment by cian-exads** [comment]
Hi @larrygrandslammedia, the issue with the above code is that the **price** parameter should be written in cents. To get a value of €1.2 euro we would need **"price": 120**. We hope this helps.

We have checked the documentation and identified that we do not clearly explain the format, which we will update as a result.

**Comment by larrygrandslammedia** [comment]
Thanks for help, cents works. Does the possible update campaign api can provide update "Marketing Material" function. it will be great for us.

**Comment by cradonn** [comment]
@larrygrandslammedia: The ability to manage assets is coming very soon in an upcoming API release.

Closing issue.
