### ISSUE TITLE
Price is wrong

### ISSUE THREAD

**Issue by wardloockx** [EXADS/exads-api-client-php#5]
When I try to get the total price of a campaign (advertiser), I came across some errors:
- When you try to get a campaign by campaignId: the price field is some odd number, and not representing the total price of the campaign.
- I use the advertiser_statistics date method now to fetch the total price. This isn't returning any summary (totals) as stated in the documentation. So I ended up doing

`$campaignInfo = $client->statistics_advertiser->date([
                        'campaignid' => $this->traffic_source_id,
                        'date-to' => '2099-01-01',
                        'date-from' => '1994-01-01',
                        'limit' => '99999999999999',
                    ]);`

and count all days together, but this is pretty dirty :-)

**Comment by tfoliveira** [comment]
Hi,

While testing point 1 with one of my own campaigns I was able to properly get the price (please be aware the price is given in cents). 

As for your second point, I'm not sure I understood which is the problem. If you decide to include totals, the response will include a "resultTotal" key with the total values for your filtering options and discarding the limit (please be aware if you don't fill in the dates, then by default they will become the current month).

You can see our API documentation for that specific route here: https://api.exoclick.com/v1/docs/#!/statistics/Get_advertiser_statistics_by_date
