### ISSUE TITLE
Exads\Client isn't extendable

### ISSUE THREAD

**Issue by seyfer** [EXADS/exads-api-client-php#7]
The problem is - I want use a proxy for sending request and for make this work I need to configure curl with couple of curl_setopt() calls.
I want extend my Client class from Exads\Client and change there method runRequest(), because this is a place where request sends. And I can't change this method because it uses couple of private properties and methods of Exads\Client. Why ? It's a very bad design.

Can you at least separate initial curl initialization in separated protected method ? For example this basic part

```
public function initCurl(array $params = []) {
$curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $this->url.$path);
        curl_setopt($curl, CURLOPT_VERBOSE, false);
        curl_setopt($curl, CURLOPT_HEADER, true);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_PORT, $this->getPort());
        if (80 !== $this->getPort()) {
            curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, $this->checkSslCertificate);
            curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, $this->checkSslHost);
        }

return $curl;
}
```

After this modification programmers will have possibility easy change this method in their inherited class using own $params.

**Comment by seyfer** [comment]
Another option is change AbstractApi class, especially it's constructor parameter. It should accept Exads\ClientInterface, not Client realization.
In this way programmer could create own Client which implements Exads\ClientInterface and inject it to concrete API class realization.

**Comment by kbsali** [comment]
@seyfer i have introduced ClientInterface as you suggested and pushed v1.2.2.
